#!/bin/bash
FILE="entschuldigung.xls"
FILEPATH="/home/shares/infodisplay"
TEMPLATEDIR="${FILEPATH}/Vorlage"
ARCHIVDIR="/media/sekretariat/MORZ/Sekretariat/Entschuldigungs-Archiv"
TIMESTAMP=$(date +'%Y-%m-%d')
DESTINATION="${ARCHIVDIR}/${TIMESTAMP}_${FILE}"
ALTERNATIVDESTINATION="${FILEPATH}/Archiv/${TIMESTAMP}_${FILE}"
sudo mount /media/sekretariat

if [ ! -d "${ARCHIVDIR}" ]
then
  cp "${FILEPATH}/${FILE}" "${ALTERNATIVDESTINATION}"
  exit 1
fi

if [ ! -f "${FILEPATH}/${FILE}" ]
then
  exit 2
fi

sudo chown pi.pi "${FILEPATH}/${FILE}"
sudo chmod 777 "${FILEPATH}/${FILE}"
cp "${FILEPATH}/${FILE}" /home/pi/ARCHIV/
cp "${FILEPATH}/${FILE}" "${DESTINATION}" && cp "${TEMPLATEDIR}/${FILE}" "${FILEPATH}/${FILE}" || exit 1
sudo chown wilma.users "${FILEPATH}/${FILE}"
/home/pi/WILMA/datum2excel.py
