#!/bin/bash
FILE="entschuldigung.xls"
FILEPATH="/home/shares/infodisplay"
TEMPLATEDIR="${FILEPATH}/Vorlage"
ARCHIVDIR="/media/sekretariat/MORZ/Sekretariat/Entschuldigungs-Archiv"
TIMESTAMP=$(date +'%Y-%m-%d')
DESTINATION="${ARCHIVDIR}/${TIMESTAMP}_${FILE}"

if [ ! -d "${ARCHIVDIR}" ]
then
  cp "${FILEPATH}/${FILE}" "${FILEPATH}/${TIMESTAMP}_${FILE}"
  exit 1
fi

if [ ! -f "${FILEPATH}/${FILE}" ]
then
  exit 2
else
  sudo chown pi.pi "${FILEPATH}/${FILE}"
  sudo chmod 777 "${FILEPATH}/${FILE}"
  cp "${FILEPATH}/${FILE}" "${DESTINATION}" && cp "${TEMPLATEDIR}/${FILE}" "${FILEPATH}/${FILE}"
  sudo chown wilma.users "${FILEPATH}/${FILE}"
  /home/pi/WILMA/datum2excel.py
fi
